version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:15.0-alpine
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    ports:
      - "${PG_PORT}:5432"

  redis:
    container_name: redis
    image: redis:7.0.5-alpine
    volumes:
      - ./docker-data/redis:/data
    ports:
      - 6379:6379

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4:6.14
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    links:
      - "postgres:pgsql-server"
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json

  redisinsight:
    container_name: redisinsight
    image: redislabs/redisinsight:1.13.0
    volumes:
      - ./docker-data/redisinsight:/db
    ports:
      - '8001:8001'
    links:
      - "redis:redis-server"
